### ISSUE TITLE
rkhunter - set package-manger to prevent false warnings

### ISSUE THREAD

**Issue by peedy2495** [mablanco/ansible-antirootkits#11]
In my case, I received these warnings:
```
Warning: The command '/usr/bin/lwp-request' has been replaced by a 
   script: /usr/bin/lwp-request: Perl script text executable
```
cause:
filehashes of package-manager deployed files has't been included due to lack of package-manager configuration.

proposal (like):
```
# here: for debian related distributions
- name: rkhunter - set package manager
  lineinfile:
    path: "/etc/rkhunter.conf"
    regexp: "(^$|^#)PKGMGR="
    line: "PKGMGR=DPKG"
    state: present
```
